"""add perfume_images table

Revision ID: 2da828d36b3d
Revises: 00aa1c0ba870
Create Date: 2026-09-30 00:22:23.433647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da828d36b3d'
down_revision: Union[str, None] = '00aa1c0ba870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfume_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfume_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['perfume_id'], ['perfumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfume_images_id'), 'perfume_images', ['id'], unique=False)
    op.create_index(op.f('ix_perfume_images_perfume_id'), 'perfume_images', ['perfume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_perfume_images_perfume_id'), table_name='perfume_images')
    op.drop_index(op.f('ix_perfume_images_id'), table_name='perfume_images')
    op.drop_table('perfume_images')
    # ### end Alembic commands ###