"""add perfume characteristics fields

Revision ID: ca1b1920f1fd
Revises: 2da828d36b3d
Create Date: 2026-09-30 23:23:20.057587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca1b1920f1fd'
down_revision: Union[str, None] = '2da828d36b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add perfume characteristics fields."""
    op.add_column(
        "perfumes",
        sa.Column("tipo", sa.String(length=100), nullable=False, server_default=""),
    )
    op.add_column(
        "perfumes",
        sa.Column("perfil", sa.Text(), nullable=False, server_default=""),
    )
    op.add_column(
        "perfumes",
        sa.Column("estilo", sa.String(length=255), nullable=False, server_default=""),
    )
    op.add_column(
        "perfumes",
        sa.Column("uso", sa.String(length=255), nullable=False, server_default=""),
    )
    op.add_column(
        "perfumes",
        sa.Column("presentacion", sa.String(length=255), nullable=False, server_default=""),
    )
    op.create_index("ix_perfumes_tipo", "perfumes", ["tipo"])



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_perfumes_tipo'), table_name='perfumes')
    op.drop_index(op.f('ix_perfumes_stock'), table_name='perfumes')
    op.drop_index(op.f('ix_perfumes_price'), table_name='perfumes')
    op.drop_index(op.f('ix_perfumes_gender'), table_name='perfumes')
    op.drop_index(op.f('ix_perfumes_family'), table_name='perfumes')
    op.drop_index(op.f('ix_perfumes_brand'), table_name='perfumes')
    op.drop_column('perfumes', 'presentacion')
    op.drop_column('perfumes', 'uso')
    op.drop_column('perfumes', 'estilo')
    op.drop_column('perfumes', 'perfil')
    op.drop_column('perfumes', 'tipo')
    # ### end Alembic commands ###